### ISSUE TITLE
Connect Muse on Mac OS 10.14.5

### ISSUE THREAD

**Issue by 360disrupt** [urish/muse-js#17]
OS: Mac OS 10.14.5
Node: 12.4

I used the Node.js example:

```
const noble = require('noble');
const bluetooth = require('bleat').webbluetooth;
const { MUSE_SERVICE, MuseClient } = require('muse-js');

async function connect() {
    let device = await bluetooth.requestDevice({
        filters: [{ services: [MUSE_SERVICE] }]
    });
    const gatt = await device.gatt.connect();
    const client = new MuseClient();
    await client.connect(gatt);
    await client.start();
    // Now do whatever with muse client...
    client.eventMarkers.subscribe((event) => {
        console.log(event);
    });
}

noble.on('stateChange', (state) => {
    if (state === 'poweredOn') {
        connect();
    }
});
```

The headset is switched on. Are there any prerequisites:
 - Do I need to connect it first to my MAC, it's not available in the Bluetooth settings, or will this be done through the app?
- I opened http://localhost:4445/ (but I guess this is just for running it in the browser, right?)
- Do I need the Mac OS SDK? The SDK seems to be deprecated and not available anymore: https://choosemuse.com/development/

I get the err after stating my index.js:

```
(node:29173) UnhandledPromiseRejectionWarning: requestDevice error: no devices found
(node:29173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

PS: I changed the package from `xpc-connection` to `xpc-connect` in noble because `xpc-connection` was deprecated.

**Comment by urish** [comment]
I'm not running on Mac OS (rather Windows), but I will try to answer based on my memory:

1. Are you using the 2016 version of the headset? the older run (I think it was 2014) doesn't run on Bluetooth Low Energy and isn't supported
2. Can you connect to the headset using your phone? Does it show up and you scan for bluetooth devices on your mac?
3. Yes, the http://localhost:4445/ address is from running within the browser. Does the browser version work? You can also try this online app: https://muse-eeg-app.firebaseapp.com/ which is based on the very same library.
4. Nope, you don't need any of the muse SDKs to work. This library implements everything from scratch.

**Comment by 360disrupt** [comment]
1 )Yes, I got the 2016 version of MUSE I. 
2) I can connect the headset to my phone, but it automatically connects to the muse app. The manual for the app also tells that it shouldn't be connected via the phones Bluetooth settings. I don't see the device on my phone/mac if I scan for Bluetooth devices.
3) The firebaseapp detects the headset and connects to it.


> Does the browser version work?
What do you mean by that? Opening the localhost does show the website is not reachable.

PS:
I wasn't able to install [`xpc-connection`](https://github.com/sandeepmistry/node-xpc-connection). The package seems to be depreceated. I installed [`xpc-connect`](https://github.com/jongear/xpc-connect) (a fork of the original package) instead and changed all refrences in the node_modules to `xpc-connect`.

**Comment by larskarbo** [comment]
@360disrupt I ran into this issue myself!

It seems to be a problem with the `noble` package not using the latest CoreBluetooth API (but using xpc-connection instead i guess).

I got `noble` working by using `noble-mac` instead. https://github.com/Timeular/noble-mac

You also have to patch the `bleat` module (because it has its own reference to `noble`). I made a repo where I monkeypatched the `bleat` module to use `noble-mac` instead. https://github.com/larskarbo/bleat-mac

So basicly you can make it work by including these two in your package json:

```json
"bleat": "https://github.com/larskarbo/bleat-mac",
"noble-mac": "https://github.com/Timeular/noble-mac.git",
```

And changing `require('noble')` to `require('noble-mac')` in your script file
```js
const noble = require('noble-mac');
const bleat = require('bleat').webbluetooth;
```

**Comment by 360disrupt** [comment]
I installed the two alternative packages. I also noticed that the headset is shown in my Mac's bluetooth devices as connected. I'm not quite sure when this happend, probably my phone shared the connection.

My code is now:

```
const noble = require('noble-mac');
const bluetooth = require('bleat').webbluetooth;
const { MUSE_SERVICE, MuseClient } = require('muse-js');

async function connect() {
    let device = await bluetooth.requestDevice({
        filters: [{ services: [MUSE_SERVICE] }]
    });
    const gatt = await device.gatt.connect();
    const client = new MuseClient();
    await client.connect(gatt);
    await client.start();
    // Now do whatever with muse client...
    client.eventMarkers.subscribe((event) => {
        console.log(event);
    });
}

noble.on('stateChange', (state) => {
    if (state === 'poweredOn') {
        connect();
    }
});
```

```
{
  "name": "brainwave",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "muse-js": "^3.1.0",
    "bleat": "https://github.com/larskarbo/bleat-mac",
    "noble-mac": "https://github.com/Timeular/noble-mac.git",
    "scribbletune": "^2.0.2"
  }
}

```

The only msg I got so far is:
`Initing modified version of bleat. (swapping noble with noble-mac) 👍`

Is there anything else I missed/need to modify?

**Comment by 360disrupt** [comment]
From the node debugger I can see:

`state` is `poweredOn`
