### ISSUE TITLE
Absolute Band Powers?

### ISSUE THREAD

**Issue by JT5D** [urish/muse-js#18]
Amazing project! Thought our new Muse (2016 model) would be unusable with our Mac/PC based neurofeedback apps until we found Muse-JS:) 

As I understand it, Muse-JS reads raw EEG data from each electrode (TP9, AF7, AF8, TP10), but is there a simple way to read absolute band powers (delta, theta, alpha, etc.), or other data, from Muse-JS, without needing to manually decode the raw EEG data from Muse-JS? 

I looked through your code, but didn't spot any way to simply parse or decode/compute band powers. Muse-IO & Muse Monitor both provided live band powers data (via OSC paths muse/elements/delta_absolute etc), as well as raw EEG data, but they're no longer feasible options & we'd love to consider using Muse-JS moving forward. Thanks for any feedback!

**Comment by urish** [comment]
Thanks!

The device itself does not calculate the absolute band powers, it has to be done at the application side. You can check out [neurosity/eeg-pipes](https://github.com/neurosity/eeg-pipes) by @alexcastillo as it might do the trick for you, I believe it can be used on top of muse-js with some adaptations.

**Comment by oori** [comment]
@JT5D there are some examples on github, see:
https://github.com/tanvach/muse-fft  (using eeg-pipes)
https://github.com/davinov/muse-js    (using dsp.js)
