### ISSUE TITLE
Unable to connect on Windows 10

### ISSUE THREAD

**Issue by Canadauni** [urish/muse-js#2]
Working on a Microsoft Surface Pro 3 running windows 10 with the Creators update and can't seem to get the web bluetooth to find the muse in my vicinity.

I added the Web Bluetooth [Polyfill](https://github.com/urish/web-bluetooth-polyfill) successfully but that doesn't seem to make a difference

The SP3 does seem to support Bluetooth LE but there might be an issue with how the driver works with Windows 10. I've ordered the ASUS BT400 adapter and will try that next but was wondering if there were any other suggestions to get this working.

**Comment by urish** [comment]
For me (on Windows 10) it sometimes takes up to a minute for the Muse device to appear. You can try with an external, Bluetooth 4.0 CSR dongle - these are cheap and they worked for me fairly well up to now, and you can even use them without the Windows BLE stack with the [Noble](https://github.com/sandeepmistry/noble#windows) project, which also means they work on older versions of windows.
