### ISSUE TITLE
Where did you get information?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [urish/muse-js#35]
I need information on Muse 2 Headband Bluetooth protocol. How did you get this information on the Muse? Can you help me?

**Comment by urish** [comment]
https://articles.jaredcamins.com/figuring-out-bluetooth-low-energy-8c2a2716e376

also https://medium.com/@urish/reactive-brain-waves-af07864bb7d4

**Comment by Shinehah-Gnolaum** [comment]
Thank you.

**Comment by Shinehah-Gnolaum** [comment]
I'm having trouble getting Core Bluetooth to work with Muse 2 Headband in iOS using Xcode.
