### ISSUE TITLE
Muse S compatibility

### ISSUE THREAD

**Issue by apavlo89** [urish/muse-js#37]
Hello,

This is a question rather than an issue. Would muse-js work with Muse S?

**Comment by urish** [comment]
No idea :) I'd also love to know

**Comment by apavlo89** [comment]
It works :)

**Comment by kylemath** [comment]
Hey @urish can I open this one back up and suggest a feature I can help with to expose the PPG data in the Muse 2 and Muse S headbands. 


based on the address of the data in the raw packets here: 
https://github.com/urish/muse-js/issues/42#issuecomment-743689736

I think the main parsing of the data files happens here: 
https://github.com/urish/muse-js/blob/master/src/muse.spec.ts

I believe a function would be needed here to parse the data, and define data types in another file:
https://github.com/urish/muse-js/blob/master/src/lib/muse-parse.ts

**Comment by kylemath** [comment]
@apavlo89 did you ever get the PPG data exposed?
