### ISSUE TITLE
Argument of type '(reading: EEGReading) => Observable<EEGReading[]>' is not assignable to paraming[]

### ISSUE THREAD

**Issue by mpastorinom** [urish/muse-js#41]
Downloaded the project and ran npn install 

![image](https://user-images.githubusercontent.com/5139772/97087126-11d54c80-15fe-11eb-9d14-4c70e2df4a35.png)

**Comment by urish** [comment]
Fixed. But in general, the project uses `yarn`

**Comment by mpastorinom** [comment]
that was really fast, thank you.
