### ISSUE TITLE
Muse S optical sensor support

### ISSUE THREAD

**Issue by kylemath** [urish/muse-js#51]
Hey @urish can I open this one back up and suggest a feature I can help with to expose the PPG data in the Muse 2 and Muse S headbands.

based on the address of the data in the raw packets here:
#42 (comment)

I think the main parsing of the data files happens here:
https://github.com/urish/muse-js/blob/master/src/muse.spec.ts

I believe a function would be needed here to parse the data, and define data types in another file:
https://github.com/urish/muse-js/blob/master/src/lib/muse-parse.ts

**Comment by CaydenPierce** [comment]
Giving this a shot.

The characteristic for PPG on Muse are defined here: https://github.com/alexandrebarachant/muse-lsl/blob/master/muselsl/constants.py

One thing worth noting is that things are different between Muse 2 and Muse S for PPG.

### Muse 2
PPG_1 - ambient
PPG_2 - infrared
PPG_3 - red

### Muse S
PPG_1 - ambient
PPG_2 - green
PPG_3 - ? (all zeros with some random ints every 10 packets or so)

### Muse Meditation App
User @chatchavan logged Muse S bluetooth packets from InterAxon Muse application here: https://github.com/ErikBjare/thesis/issues/9  

He said they are only using PPG_2 and assumes that it's the green light.

## Result
Let's subscribe to and supply PPG_1, PPG_2, and PPG_3. Library users can determine which channel they want to use.

**Comment by kylemath** [comment]
Good, plan, we should get our hands on a muse S2 and see if its different

**Comment by CaydenPierce** [comment]
Working on this here: https://github.com/CaydenPierce/muse-js/tree/ppg

**Comment by kylemath** [comment]
Great
