### ISSUE TITLE
Source code for https://muse-eeg-app.firebaseapp.com/

### ISSUE THREAD

**Issue by mayeaux** [urish/muse-js#6]
Hey there, cool project! I was wondering if the source code for https://muse-eeg-app.firebaseapp.com/ was available somewhere? The demo app in this repo is much more bare-bones, thanks!

**Comment by mayeaux** [comment]
Found it, thanks!

**Comment by urish** [comment]
Thank you! For future people looking for the source code - the most up to date version is here:

https://github.com/urish/eeg-explorer
