### ISSUE TITLE
question about unsubscribing

### ISSUE THREAD

**Issue by masseyl** [urish/muse-js#9]
Hey,

Not an issue, just a question. I've noticed the Client doesn't have an "unsubscribe" function - is that automatic on disconnect()? I ask because I'm going to be using it in an office setting, so I want to make certain Person A's dataset doesn't accidentally get mixed with Person N's.

**Comment by urish** [comment]
Yes, this is handled by the [observableCharacteristic](https://github.com/urish/muse-js/blob/f905fccdcd1a0accb732d7759fa2d53acaa89a10/src/lib/muse-utils.ts#L14) helper method - you can see it also listens for device disconnect events, and closes the subscription as soon as one is emitted.
